/**
 * Cycle Discovery Service
 *
 * Discovers catalytic nuclear reaction cycles from the Parkhomov database.
 * A catalytic cycle is one where an intermediate nuclide is consumed in one
 * reaction and regenerated by a later reaction (e.g., the CNO cycle where
 * C-12 is consumed then regenerated).
 *
 * Algorithm:
 * 1. Build a reaction graph from fusion, two-to-two, and optionally fission reactions
 * 2. Generate fuel candidates (singles and pairs of nuclides)
 * 3. DFS-based cycle detection: track consumed/regenerated nuclides
 * 4. Score and rank discovered cycles
 */

import type { Database } from 'sql.js';
import type {
  CycleDiscoveryParameters,
  CycleDiscoveryResults,
  CycleDiscoveryProgress,
  DiscoveredCycle,
  CycleReaction,
} from '../types';

// ---------------------------------------------------------------------------
// Internal types
// ---------------------------------------------------------------------------

interface NuclideRef {
  E: string;
  Z: number;
  A: number;
}

interface ReactionEdge {
  type: 'fusion' | 'twotwo' | 'fission';
  inputs: NuclideRef[];
  outputs: NuclideRef[];
  MeV: number;
}

/** Adjacency list: nuclideId -> reactions where this nuclide is an input */
type ReactionGraph = Map<string, ReactionEdge[]>;

interface NuclideMetadata {
  Z: number;
  ppmNSolar: number | null;
  LHL: number | null;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function nuclideId(E: string, A: number): string {
  return `${E}-${A}`;
}

function refToId(ref: NuclideRef): string {
  return nuclideId(ref.E, ref.A);
}

/**
 * Simple string hash for generating deterministic cycle IDs.
 * Uses a djb2-style hash, returning a hex string.
 */
function hashString(str: string): string {
  let hash = 5381;
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) + hash + str.charCodeAt(i)) | 0;
  }
  return (hash >>> 0).toString(16).padStart(8, '0');
}

/**
 * Generate a unique cycle ID from its reactions by sorting and hashing
 * the reaction signatures.
 */
function generateCycleId(reactions: CycleReaction[]): string {
  const signatures = reactions.map(r => {
    const inputStr = r.inputs.map(n => refToId(n)).sort().join('+');
    const outputStr = r.outputs.map(n => refToId(n)).sort().join('+');
    return `${r.type}:${inputStr}->${outputStr}`;
  });
  signatures.sort();
  return hashString(signatures.join('|'));
}

/**
 * Validate that a string is a valid element symbol (1-3 letters only).
 * Valid examples: H, He, Li, Uue. This strict validation prevents SQL
 * injection since element symbols are interpolated into SQL IN() clauses.
 */
function isValidElementSymbol(symbol: string): boolean {
  return /^[A-Za-z]{1,3}$/.test(symbol);
}

/**
 * Build an SQL-safe quoted element list string from an array of element symbols.
 * Each symbol is validated to contain only letters (1-3 chars) before inclusion,
 * preventing SQL injection even though values are interpolated into queries.
 */
function quotedElementList(elements: string[]): string {
  const sanitized = elements.filter(isValidElementSymbol);
  return sanitized.map(e => `'${e}'`).join(',');
}

// ---------------------------------------------------------------------------
// Step 1: Build the reaction graph
// ---------------------------------------------------------------------------

function loadNuclideMetadata(db: Database): Map<string, NuclideMetadata> {
  const meta = new Map<string, NuclideMetadata>();
  const sql = 'SELECT Z, A, E, ppmNSolar, LHL FROM NuclidesPlus';
  const results = db.exec(sql);
  if (results.length > 0) {
    for (const row of results[0].values) {
      const [Z, A, E, ppmNSolar, LHL] = row as [number, number, string, number | null, number | null];
      const id = nuclideId(E, A);
      meta.set(id, { Z, ppmNSolar, LHL });
    }
  }
  return meta;
}

function buildReactionGraph(
  db: Database,
  params: CycleDiscoveryParameters,
  nuclideMetadata: Map<string, NuclideMetadata>,
  shouldCancel?: () => boolean
): ReactionGraph {
  const graph: ReactionGraph = new Map();

  // Determine allowed elements filter
  const allowedElements = params.elementFilters?.allowedElements;
  const abundantOnly = params.elementFilters?.abundantOnly ?? false;
  const excludeRadioactive = params.elementFilters?.excludeRadioactive ?? false;

  // Build a set of allowed nuclide IDs for filtering
  let allowedNuclideIds: Set<string> | null = null;
  if (abundantOnly || excludeRadioactive) {
    allowedNuclideIds = new Set<string>();
    for (const [id, meta] of nuclideMetadata) {
      if (abundantOnly && (meta.ppmNSolar === null || meta.ppmNSolar <= 0)) continue;
      if (excludeRadioactive && (meta.LHL === null || meta.LHL <= 9)) continue;
      allowedNuclideIds.add(id);
    }
  }

  function isNuclideAllowed(ref: NuclideRef): boolean {
    if (allowedNuclideIds !== null) {
      return allowedNuclideIds.has(refToId(ref));
    }
    return true;
  }

  function addEdge(edge: ReactionEdge): void {
    // Check all nuclides in the reaction are allowed
    for (const ref of [...edge.inputs, ...edge.outputs]) {
      if (!isNuclideAllowed(ref)) return;
    }

    // Add to adjacency list: index by each input nuclide
    for (const input of edge.inputs) {
      const id = refToId(input);
      if (!graph.has(id)) {
        graph.set(id, []);
      }
      graph.get(id)!.push(edge);
    }
  }

  // Build element filter clause
  let elementsStr: string;
  if (allowedElements && allowedElements.length > 0) {
    elementsStr = quotedElementList(allowedElements);
    // If all user-provided elements were invalid, fall back to all elements
    if (elementsStr === '') {
      const elemResult = db.exec('SELECT DISTINCT E FROM NuclidesPlus');
      if (elemResult.length === 0) return graph;
      const allElements = elemResult[0].values.map(row => row[0] as string);
      elementsStr = quotedElementList(allElements);
    }
  } else {
    // Get all distinct elements from the database
    const elemResult = db.exec('SELECT DISTINCT E FROM NuclidesPlus');
    if (elemResult.length === 0) return graph;
    const allElements = elemResult[0].values.map(row => row[0] as string);
    elementsStr = quotedElementList(allElements);
  }

  // Query fusion reactions: A + B -> C
  const fusionQuery = `
    SELECT E1, Z1, A1, E2, Z2, A2, E, Z, A, MeV, neutrino
    FROM FusionAll
    WHERE E1 IN (${elementsStr}) AND E2 IN (${elementsStr})
      AND MeV >= ${params.minFusionMeV}
    LIMIT 50000
  `;
  const fusionResults = db.exec(fusionQuery);
  if (fusionResults.length > 0) {
    for (const row of fusionResults[0].values) {
      const [E1, Z1, A1, E2, Z2, A2, E, Z, A, MeV] = row as [
        string, number, number, string, number, number,
        string, number, number, number, string
      ];
      addEdge({
        type: 'fusion',
        inputs: [
          { E: E1, Z: Z1, A: A1 },
          { E: E2, Z: Z2, A: A2 },
        ],
        outputs: [{ E, Z, A }],
        MeV,
      });
    }
  }

  if (shouldCancel?.()) {
    throw new Error('Cycle discovery cancelled');
  }

  // Query two-to-two reactions: A + B -> C + D
  const twoToTwoQuery = `
    SELECT E1, Z1, A1, E2, Z2, A2, E3, Z3, A3, E4, Z4, A4, MeV, neutrino
    FROM TwoToTwoAll
    WHERE E1 IN (${elementsStr}) AND E2 IN (${elementsStr})
      AND MeV >= ${params.minTwoToTwoMeV}
    LIMIT 50000
  `;
  const twoToTwoResults = db.exec(twoToTwoQuery);
  if (twoToTwoResults.length > 0) {
    for (const row of twoToTwoResults[0].values) {
      const [E1, Z1, A1, E2, Z2, A2, E3, Z3, A3, E4, Z4, A4, MeV] = row as [
        string, number, number, string, number, number,
        string, number, number, string, number, number, number, string
      ];
      addEdge({
        type: 'twotwo',
        inputs: [
          { E: E1, Z: Z1, A: A1 },
          { E: E2, Z: Z2, A: A2 },
        ],
        outputs: [
          { E: E3, Z: Z3, A: A3 },
          { E: E4, Z: Z4, A: A4 },
        ],
        MeV,
      });
    }
  }

  if (shouldCancel?.()) {
    throw new Error('Cycle discovery cancelled');
  }

  // Query fission reactions: A -> B + C (if enabled)
  if (params.includeFission) {
    const minFissionMeV = params.minFissionMeV ?? 0;
    const fissionQuery = `
      SELECT E, Z, A, E1, Z1, A1, E2, Z2, A2, MeV, neutrino
      FROM FissionAll
      WHERE E IN (${elementsStr})
        AND MeV >= ${minFissionMeV}
      LIMIT 50000
    `;
    const fissionResults = db.exec(fissionQuery);
    if (fissionResults.length > 0) {
      for (const row of fissionResults[0].values) {
        const [E, Z, A, E1, Z1, A1, E2, Z2, A2, MeV] = row as [
          string, number, number, string, number, number,
          string, number, number, number, string
        ];
        addEdge({
          type: 'fission',
          inputs: [{ E, Z, A }],
          outputs: [
            { E: E1, Z: Z1, A: A1 },
            { E: E2, Z: Z2, A: A2 },
          ],
          MeV,
        });
      }
    }

    if (shouldCancel?.()) {
      throw new Error('Cycle discovery cancelled');
    }
  }

  return graph;
}

// ---------------------------------------------------------------------------
// Step 2: Generate fuel candidates
// ---------------------------------------------------------------------------

interface FuelCandidate {
  nuclides: string[];
}

function generateFuelCandidates(
  graph: ReactionGraph,
  shouldCancel?: () => boolean
): FuelCandidate[] {
  const candidates: FuelCandidate[] = [];
  const allNuclides = Array.from(graph.keys());

  // All singles
  for (const n of allNuclides) {
    candidates.push({ nuclides: [n] });
  }

  // Pairs from top 50 most-connected nuclides to avoid combinatorial explosion
  const sortedByConnections = [...allNuclides]
    .map(n => ({ id: n, count: graph.get(n)?.length ?? 0 }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 50)
    .map(n => n.id);

  for (let i = 0; i < sortedByConnections.length; i++) {
    if (shouldCancel?.()) {
      throw new Error('Cycle discovery cancelled');
    }
    for (let j = i + 1; j < sortedByConnections.length; j++) {
      candidates.push({ nuclides: [sortedByConnections[i], sortedByConnections[j]] });
    }
  }

  return candidates;
}

// ---------------------------------------------------------------------------
// Step 3: DFS-based cycle finder
// ---------------------------------------------------------------------------

interface CycleCandidate {
  reactions: CycleReaction[];
  fuelNuclides: NuclideRef[];
}

/**
 * Find catalytic cycles starting from a given fuel set.
 *
 * The algorithm maintains a "pool" of available nuclides. At each step:
 * - Find reactions where ALL inputs are in the pool
 * - Execute a reaction: remove consumed inputs, add outputs
 * - A CYCLE is detected when a nuclide that was consumed earlier reappears
 *   as an output of a later reaction
 * - Backtrack and explore other paths
 */
function findCyclesFromFuel(
  graph: ReactionGraph,
  fuelSet: string[],
  maxDepth: number,
  nuclideMetadata: Map<string, NuclideMetadata>,
  shouldCancel?: () => boolean
): CycleCandidate[] {
  const found: CycleCandidate[] = [];
  // Limit total cycles found per fuel set to avoid excessive computation
  const maxPerFuel = 20;

  // Build a lookup map from nuclide ID to its NuclideRef from the graph edges
  const nuclideRefMap = new Map<string, NuclideRef>();
  for (const edges of graph.values()) {
    for (const edge of edges) {
      for (const ref of [...edge.inputs, ...edge.outputs]) {
        nuclideRefMap.set(refToId(ref), ref);
      }
    }
  }

  // Pool tracks what nuclides are available
  const pool = new Set<string>(fuelSet);
  // Consumed tracks which nuclides have been consumed (used as inputs)
  const consumed = new Set<string>();
  // Path of reactions taken so far
  const path: ReactionEdge[] = [];
  // Track visited states to prune search (reaction signature at each depth)
  const visitedAtDepth = new Set<string>();

  function dfs(): void {
    if (found.length >= maxPerFuel) return;
    if (path.length >= maxDepth) return;

    // Collect all candidate reactions from pool nuclides
    const candidateReactions: ReactionEdge[] = [];
    const seen = new Set<string>();

    for (const nuclideInPool of pool) {
      const edges = graph.get(nuclideInPool);
      if (!edges) continue;

      for (const edge of edges) {
        // Check all inputs are in the pool
        const allInputsAvailable = edge.inputs.every(inp => pool.has(refToId(inp)));
        if (!allInputsAvailable) continue;

        // Create a signature to avoid processing the same reaction twice
        const sig = `${edge.type}:${edge.inputs.map(r => refToId(r)).sort().join('+')}=>${edge.outputs.map(r => refToId(r)).sort().join('+')}`;
        if (seen.has(sig)) continue;
        seen.add(sig);

        // Avoid repeating exact same state at same depth
        const stateSig = `${path.length}:${sig}`;
        if (visitedAtDepth.has(stateSig)) continue;
        visitedAtDepth.add(stateSig);

        candidateReactions.push(edge);
      }
    }

    for (const edge of candidateReactions) {
      if (found.length >= maxPerFuel) return;
      if (shouldCancel?.()) {
        throw new Error('Cycle discovery cancelled');
      }

      // "Execute" the reaction
      const inputIds = edge.inputs.map(r => refToId(r));
      const outputIds = edge.outputs.map(r => refToId(r));

      // Track which inputs are consumed (removed from pool)
      const newlyConsumed: string[] = [];
      for (const inputId of inputIds) {
        if (!fuelSet.includes(inputId)) {
          // Non-fuel inputs are consumed
          consumed.add(inputId);
          newlyConsumed.push(inputId);
          pool.delete(inputId);
        }
      }

      // Add outputs to pool
      const addedOutputs: string[] = [];
      for (const outputId of outputIds) {
        if (!pool.has(outputId)) {
          pool.add(outputId);
          addedOutputs.push(outputId);
        }
      }

      path.push(edge);

      // Check for cycle: an output regenerates a previously consumed nuclide
      const regenerated = outputIds.filter(id => consumed.has(id));
      if (regenerated.length > 0 && path.length >= 2) {
        // We found a cycle -- build the CycleCandidate
        const reactions: CycleReaction[] = path.map((e) => {
          // Determine if this reaction's output regenerates a consumed nuclide
          const outputsOfReaction = e.outputs.map(r => refToId(r));
          const isFeedback = outputsOfReaction.some(id => consumed.has(id));

          return {
            type: e.type,
            inputs: e.inputs.map(r => ({ ...r })),
            outputs: e.outputs.map(r => ({ ...r })),
            MeV: e.MeV,
            isFeedback,
          };
        });

        const fuelNuclides = fuelSet.map(id => {
          const ref = nuclideRefMap.get(id);
          if (ref) return { ...ref };
          const [E, aStr] = id.split('-');
          const A = parseInt(aStr, 10);
          const meta = nuclideMetadata.get(id);
          return { E, Z: meta?.Z ?? 0, A };
        });

        found.push({ reactions, fuelNuclides });
      }

      // Continue DFS deeper
      dfs();

      // Backtrack: restore pool state
      path.pop();
      for (const id of addedOutputs) {
        pool.delete(id);
      }
      for (const id of newlyConsumed) {
        consumed.delete(id);
        pool.add(id);
      }
    }
  }

  dfs();
  return found;
}

// ---------------------------------------------------------------------------
// Step 4: Score a cycle
// ---------------------------------------------------------------------------

function scoreCycle(
  reactions: CycleReaction[],
  fuelNuclides: NuclideRef[],
  nuclideMetadata: Map<string, NuclideMetadata>
): { totalEnergy: number; feedbackRatio: number; abundanceScore: number; stabilityScore: number } {
  // Total energy
  const totalEnergy = reactions.reduce((sum, r) => sum + r.MeV, 0);

  // Feedback ratio: fraction of reactions where an output regenerates a consumed nuclide
  const feedbackCount = reactions.filter(r => r.isFeedback).length;
  const feedbackRatio = reactions.length > 0 ? (feedbackCount / reactions.length) * 100 : 0;

  // Collect all unique nuclides in the cycle
  const allNuclideIds = new Set<string>();
  for (const r of reactions) {
    for (const ref of [...r.inputs, ...r.outputs]) {
      allNuclideIds.add(refToId(ref));
    }
  }
  for (const ref of fuelNuclides) {
    allNuclideIds.add(refToId(ref));
  }

  // Abundance score: average of log10(ppmNSolar), normalized to 0-100
  // Hydrogen has ppmNSolar ~ 739000 => log10 ~ 5.87
  // We normalize so that log10(739000) ~ 5.87 maps to 100
  const maxLogAbundance = 5.87; // log10 of hydrogen solar abundance
  let abundanceSum = 0;
  let abundanceCount = 0;
  for (const id of allNuclideIds) {
    const meta = nuclideMetadata.get(id);
    if (meta && meta.ppmNSolar !== null && meta.ppmNSolar > 0) {
      abundanceSum += Math.log10(meta.ppmNSolar);
      abundanceCount++;
    }
  }
  const abundanceScore = abundanceCount > 0
    ? Math.max(0, Math.min(100, (abundanceSum / abundanceCount / maxLogAbundance) * 100))
    : 0;

  // Stability score: fraction of nuclides with logHalfLife > 9
  let stableCount = 0;
  let totalNuclides = 0;
  for (const id of allNuclideIds) {
    totalNuclides++;
    const meta = nuclideMetadata.get(id);
    if (meta && meta.LHL !== null && meta.LHL > 9) {
      stableCount++;
    }
  }
  const stabilityScore = totalNuclides > 0
    ? (stableCount / totalNuclides) * 100
    : 0;

  return { totalEnergy, feedbackRatio, abundanceScore, stabilityScore };
}

// ---------------------------------------------------------------------------
// Step 5: Deduplication
// ---------------------------------------------------------------------------

function deduplicateCycles(cycles: CycleCandidate[]): CycleCandidate[] {
  const seen = new Set<string>();
  const unique: CycleCandidate[] = [];

  for (const cycle of cycles) {
    const id = generateCycleId(cycle.reactions);
    if (!seen.has(id)) {
      seen.add(id);
      unique.push(cycle);
    }
  }

  return unique;
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

/**
 * Discover catalytic nuclear reaction cycles from the database.
 *
 * @param db - sql.js Database instance
 * @param params - Discovery parameters (energy thresholds, depth, filters)
 * @param onProgress - Optional callback for progress updates
 * @returns Discovered cycles ranked by total energy
 */
export function discoverCycles(
  db: Database,
  params: CycleDiscoveryParameters,
  onProgress?: (progress: CycleDiscoveryProgress) => void,
  shouldCancel?: () => boolean
): CycleDiscoveryResults {
  const startTime = performance.now();

  // Load nuclide metadata for scoring
  const nuclideMetadata = loadNuclideMetadata(db);

  // Phase 1: Build graph
  onProgress?.({
    phase: 'building_graph',
    cyclesFound: 0,
    fuelCombinationsChecked: 0,
    totalCombinations: 0,
    percentage: 0,
  });

  const graph = buildReactionGraph(db, params, nuclideMetadata, shouldCancel);

  // Phase 2: Search for cycles
  const fuelCandidates = generateFuelCandidates(graph, shouldCancel);
  const totalCombinations = fuelCandidates.length;

  onProgress?.({
    phase: 'searching_cycles',
    cyclesFound: 0,
    fuelCombinationsChecked: 0,
    totalCombinations,
    percentage: 0,
  });

  const allCandidates: CycleCandidate[] = [];
  let checkedCount = 0;

  for (let i = 0; i < fuelCandidates.length; i++) {
    if (shouldCancel?.()) {
      throw new Error('Cycle discovery cancelled');
    }
    const candidate = fuelCandidates[i];
    const cycles = findCyclesFromFuel(graph, candidate.nuclides, params.maxCycleDepth, nuclideMetadata, shouldCancel);
    allCandidates.push(...cycles);
    checkedCount = i + 1;

    // Report progress periodically (every 50 candidates or when cycles are found)
    if (i % 50 === 0 || cycles.length > 0) {
      onProgress?.({
        phase: 'searching_cycles',
        cyclesFound: allCandidates.length,
        fuelCombinationsChecked: checkedCount,
        totalCombinations,
        percentage: Math.round((checkedCount / totalCombinations) * 100),
      });
    }

    // Early termination if we have enough candidates (with buffer for dedup)
    if (allCandidates.length >= params.maxCycles * 3) break;
  }

  // Phase 3: Deduplicate, score, and rank
  onProgress?.({
    phase: 'ranking',
    cyclesFound: allCandidates.length,
    fuelCombinationsChecked: checkedCount,
    totalCombinations,
    percentage: 95,
  });

  const uniqueCandidates = deduplicateCycles(allCandidates);

  // Score all unique cycles
  const scoredCycles: DiscoveredCycle[] = uniqueCandidates.map(candidate => {
    const scores = scoreCycle(candidate.reactions, candidate.fuelNuclides, nuclideMetadata);
    const id = generateCycleId(candidate.reactions);

    return {
      id,
      fuelNuclides: candidate.fuelNuclides,
      reactions: candidate.reactions,
      totalEnergy: scores.totalEnergy,
      feedbackRatio: scores.feedbackRatio,
      cycleDepth: candidate.reactions.length,
      abundanceScore: scores.abundanceScore,
      stabilityScore: scores.stabilityScore,
    };
  });

  // Sort by total energy descending (highest energy cycles first)
  scoredCycles.sort((a, b) => b.totalEnergy - a.totalEnergy);

  // Limit to maxCycles
  const topCycles = scoredCycles.slice(0, params.maxCycles);

  const executionTime = performance.now() - startTime;

  onProgress?.({
    phase: 'ranking',
    cyclesFound: topCycles.length,
    fuelCombinationsChecked: totalCombinations,
    totalCombinations,
    percentage: 100,
  });

  return {
    cycles: topCycles,
    executionTime,
    totalCyclesFound: scoredCycles.length,
  };
}
