/**
 * IAEA isotopic abundance data
 *
 * Source: IAEA Nuclear Data Services - LiveChart API
 * URL: https://nds.iaea.org/relnsd/v1/data?fields=ground_states&nuclides=all
 * Data vintage: NuBase 2020 / NUBASE2020 evaluation
 * Extracted: 2026-03-02
 *
 * Values are natural isotopic abundance percentages (mole fraction * 100).
 * Uncertainties are in the same units.
 *
 * This file is auto-generated by scripts/fetch-iaea-abundances.js
 * Do not edit manually.
 */

export interface IAEAAbundance {
  /** Atomic number */
  z: number
  /** Mass number */
  a: number
  /** Element symbol (uses D/T for deuterium/tritium to match Parkhomov convention) */
  symbol: string
  /** Natural isotopic abundance (%) */
  abundance: number
  /** Uncertainty on abundance (%) or null if not available */
  uncertainty: number | null
}

/**
 * IAEA isotopic abundance data for 288 naturally occurring nuclides
 * across 84 elements.
 */
export const IAEA_ABUNDANCES: IAEAAbundance[] = [
  {
    "z": 1,
    "a": 1,
    "symbol": "H",
    "abundance": 99.9855,
    "uncertainty": 0.0078
  },
  {
    "z": 1,
    "a": 2,
    "symbol": "D",
    "abundance": 0.0145,
    "uncertainty": 0.0078
  },
  {
    "z": 2,
    "a": 3,
    "symbol": "He",
    "abundance": 0.0002,
    "uncertainty": 0.0002
  },
  {
    "z": 2,
    "a": 4,
    "symbol": "He",
    "abundance": 99.9998,
    "uncertainty": 0.0002
  },
  {
    "z": 3,
    "a": 6,
    "symbol": "Li",
    "abundance": 4.85,
    "uncertainty": 1.71
  },
  {
    "z": 3,
    "a": 7,
    "symbol": "Li",
    "abundance": 95.15,
    "uncertainty": 1.71
  },
  {
    "z": 4,
    "a": 9,
    "symbol": "Be",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 5,
    "a": 10,
    "symbol": "B",
    "abundance": 19.65,
    "uncertainty": 0.44
  },
  {
    "z": 5,
    "a": 11,
    "symbol": "B",
    "abundance": 80.35,
    "uncertainty": 0.44
  },
  {
    "z": 6,
    "a": 12,
    "symbol": "C",
    "abundance": 98.94,
    "uncertainty": 0.06
  },
  {
    "z": 6,
    "a": 13,
    "symbol": "C",
    "abundance": 1.06,
    "uncertainty": 0.06
  },
  {
    "z": 7,
    "a": 14,
    "symbol": "N",
    "abundance": 99.6205,
    "uncertainty": 0.0247
  },
  {
    "z": 7,
    "a": 15,
    "symbol": "N",
    "abundance": 0.3795,
    "uncertainty": 0.0247
  },
  {
    "z": 8,
    "a": 16,
    "symbol": "O",
    "abundance": 99.757,
    "uncertainty": 0.011
  },
  {
    "z": 8,
    "a": 17,
    "symbol": "O",
    "abundance": 0.0384,
    "uncertainty": 0.001
  },
  {
    "z": 8,
    "a": 18,
    "symbol": "O",
    "abundance": 0.2045,
    "uncertainty": 0.0102
  },
  {
    "z": 9,
    "a": 19,
    "symbol": "F",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 10,
    "a": 20,
    "symbol": "Ne",
    "abundance": 90.48,
    "uncertainty": 0.03
  },
  {
    "z": 10,
    "a": 21,
    "symbol": "Ne",
    "abundance": 0.27,
    "uncertainty": 0.01
  },
  {
    "z": 10,
    "a": 22,
    "symbol": "Ne",
    "abundance": 9.25,
    "uncertainty": 0.03
  },
  {
    "z": 11,
    "a": 23,
    "symbol": "Na",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 12,
    "a": 24,
    "symbol": "Mg",
    "abundance": 78.965,
    "uncertainty": 0.049
  },
  {
    "z": 12,
    "a": 25,
    "symbol": "Mg",
    "abundance": 10.011,
    "uncertainty": 0.013
  },
  {
    "z": 12,
    "a": 26,
    "symbol": "Mg",
    "abundance": 11.025,
    "uncertainty": 0.038
  },
  {
    "z": 13,
    "a": 27,
    "symbol": "Al",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 14,
    "a": 28,
    "symbol": "Si",
    "abundance": 92.2545,
    "uncertainty": 0.0037
  },
  {
    "z": 14,
    "a": 29,
    "symbol": "Si",
    "abundance": 4.672,
    "uncertainty": 0.016
  },
  {
    "z": 14,
    "a": 30,
    "symbol": "Si",
    "abundance": 3.0735,
    "uncertainty": 0.0021
  },
  {
    "z": 15,
    "a": 31,
    "symbol": "P",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 16,
    "a": 32,
    "symbol": "S",
    "abundance": 94.85,
    "uncertainty": 0.255
  },
  {
    "z": 16,
    "a": 33,
    "symbol": "S",
    "abundance": 0.763,
    "uncertainty": 0.02
  },
  {
    "z": 16,
    "a": 34,
    "symbol": "S",
    "abundance": 4.365,
    "uncertainty": 0.235
  },
  {
    "z": 16,
    "a": 36,
    "symbol": "S",
    "abundance": 0.0158,
    "uncertainty": 0.0017
  },
  {
    "z": 17,
    "a": 35,
    "symbol": "Cl",
    "abundance": 75.8,
    "uncertainty": 0.17
  },
  {
    "z": 17,
    "a": 37,
    "symbol": "Cl",
    "abundance": 24.2,
    "uncertainty": 0.17
  },
  {
    "z": 18,
    "a": 36,
    "symbol": "Ar",
    "abundance": 0.3336,
    "uncertainty": 0.021
  },
  {
    "z": 18,
    "a": 38,
    "symbol": "Ar",
    "abundance": 0.0629,
    "uncertainty": 0.007
  },
  {
    "z": 18,
    "a": 40,
    "symbol": "Ar",
    "abundance": 99.6035,
    "uncertainty": 0.025
  },
  {
    "z": 19,
    "a": 39,
    "symbol": "K",
    "abundance": 93.2581,
    "uncertainty": 0.0044
  },
  {
    "z": 19,
    "a": 40,
    "symbol": "K",
    "abundance": 0.0117,
    "uncertainty": 0.0001
  },
  {
    "z": 19,
    "a": 41,
    "symbol": "K",
    "abundance": 6.7302,
    "uncertainty": 0.0044
  },
  {
    "z": 20,
    "a": 40,
    "symbol": "Ca",
    "abundance": 96.941,
    "uncertainty": 0.156
  },
  {
    "z": 20,
    "a": 42,
    "symbol": "Ca",
    "abundance": 0.647,
    "uncertainty": 0.023
  },
  {
    "z": 20,
    "a": 43,
    "symbol": "Ca",
    "abundance": 0.135,
    "uncertainty": 0.01
  },
  {
    "z": 20,
    "a": 44,
    "symbol": "Ca",
    "abundance": 2.086,
    "uncertainty": 0.11
  },
  {
    "z": 20,
    "a": 46,
    "symbol": "Ca",
    "abundance": 0.004,
    "uncertainty": 0.003
  },
  {
    "z": 20,
    "a": 48,
    "symbol": "Ca",
    "abundance": 0.187,
    "uncertainty": 0.021
  },
  {
    "z": 21,
    "a": 45,
    "symbol": "Sc",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 22,
    "a": 46,
    "symbol": "Ti",
    "abundance": 8.25,
    "uncertainty": 0.03
  },
  {
    "z": 22,
    "a": 47,
    "symbol": "Ti",
    "abundance": 7.44,
    "uncertainty": 0.02
  },
  {
    "z": 22,
    "a": 48,
    "symbol": "Ti",
    "abundance": 73.72,
    "uncertainty": 0.03
  },
  {
    "z": 22,
    "a": 49,
    "symbol": "Ti",
    "abundance": 5.41,
    "uncertainty": 0.02
  },
  {
    "z": 22,
    "a": 50,
    "symbol": "Ti",
    "abundance": 5.18,
    "uncertainty": 0.02
  },
  {
    "z": 23,
    "a": 50,
    "symbol": "V",
    "abundance": 0.25,
    "uncertainty": 0.01
  },
  {
    "z": 23,
    "a": 51,
    "symbol": "V",
    "abundance": 99.75,
    "uncertainty": 0.01
  },
  {
    "z": 24,
    "a": 50,
    "symbol": "Cr",
    "abundance": 4.345,
    "uncertainty": 0.013
  },
  {
    "z": 24,
    "a": 52,
    "symbol": "Cr",
    "abundance": 83.789,
    "uncertainty": 0.018
  },
  {
    "z": 24,
    "a": 53,
    "symbol": "Cr",
    "abundance": 9.501,
    "uncertainty": 0.017
  },
  {
    "z": 24,
    "a": 54,
    "symbol": "Cr",
    "abundance": 2.365,
    "uncertainty": 0.007
  },
  {
    "z": 25,
    "a": 55,
    "symbol": "Mn",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 26,
    "a": 54,
    "symbol": "Fe",
    "abundance": 5.845,
    "uncertainty": 0.105
  },
  {
    "z": 26,
    "a": 56,
    "symbol": "Fe",
    "abundance": 91.754,
    "uncertainty": 0.106
  },
  {
    "z": 26,
    "a": 57,
    "symbol": "Fe",
    "abundance": 2.119,
    "uncertainty": 0.029
  },
  {
    "z": 26,
    "a": 58,
    "symbol": "Fe",
    "abundance": 0.282,
    "uncertainty": 0.012
  },
  {
    "z": 27,
    "a": 59,
    "symbol": "Co",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 28,
    "a": 58,
    "symbol": "Ni",
    "abundance": 68.0769,
    "uncertainty": 0.019
  },
  {
    "z": 28,
    "a": 60,
    "symbol": "Ni",
    "abundance": 26.2231,
    "uncertainty": 0.015
  },
  {
    "z": 28,
    "a": 61,
    "symbol": "Ni",
    "abundance": 1.1399,
    "uncertainty": 0.0013
  },
  {
    "z": 28,
    "a": 62,
    "symbol": "Ni",
    "abundance": 3.6345,
    "uncertainty": 0.004
  },
  {
    "z": 28,
    "a": 64,
    "symbol": "Ni",
    "abundance": 0.9256,
    "uncertainty": 0.0019
  },
  {
    "z": 29,
    "a": 63,
    "symbol": "Cu",
    "abundance": 69.15,
    "uncertainty": 0.15
  },
  {
    "z": 29,
    "a": 65,
    "symbol": "Cu",
    "abundance": 30.85,
    "uncertainty": 0.15
  },
  {
    "z": 30,
    "a": 64,
    "symbol": "Zn",
    "abundance": 49.17,
    "uncertainty": 0.75
  },
  {
    "z": 30,
    "a": 66,
    "symbol": "Zn",
    "abundance": 27.73,
    "uncertainty": 0.98
  },
  {
    "z": 30,
    "a": 67,
    "symbol": "Zn",
    "abundance": 4.04,
    "uncertainty": 0.16
  },
  {
    "z": 30,
    "a": 68,
    "symbol": "Zn",
    "abundance": 18.45,
    "uncertainty": 0.63
  },
  {
    "z": 30,
    "a": 70,
    "symbol": "Zn",
    "abundance": 0.61,
    "uncertainty": 0.1
  },
  {
    "z": 31,
    "a": 69,
    "symbol": "Ga",
    "abundance": 60.108,
    "uncertainty": 0.05
  },
  {
    "z": 31,
    "a": 71,
    "symbol": "Ga",
    "abundance": 39.892,
    "uncertainty": 0.05
  },
  {
    "z": 32,
    "a": 70,
    "symbol": "Ge",
    "abundance": 20.52,
    "uncertainty": 0.19
  },
  {
    "z": 32,
    "a": 72,
    "symbol": "Ge",
    "abundance": 27.45,
    "uncertainty": 0.15
  },
  {
    "z": 32,
    "a": 73,
    "symbol": "Ge",
    "abundance": 7.76,
    "uncertainty": 0.08
  },
  {
    "z": 32,
    "a": 74,
    "symbol": "Ge",
    "abundance": 36.52,
    "uncertainty": 0.12
  },
  {
    "z": 32,
    "a": 76,
    "symbol": "Ge",
    "abundance": 7.75,
    "uncertainty": 0.12
  },
  {
    "z": 33,
    "a": 75,
    "symbol": "As",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 34,
    "a": 74,
    "symbol": "Se",
    "abundance": 0.86,
    "uncertainty": 0.03
  },
  {
    "z": 34,
    "a": 76,
    "symbol": "Se",
    "abundance": 9.23,
    "uncertainty": 0.07
  },
  {
    "z": 34,
    "a": 77,
    "symbol": "Se",
    "abundance": 7.6,
    "uncertainty": 0.07
  },
  {
    "z": 34,
    "a": 78,
    "symbol": "Se",
    "abundance": 23.69,
    "uncertainty": 0.22
  },
  {
    "z": 34,
    "a": 80,
    "symbol": "Se",
    "abundance": 49.8,
    "uncertainty": 0.36
  },
  {
    "z": 34,
    "a": 82,
    "symbol": "Se",
    "abundance": 8.82,
    "uncertainty": 0.15
  },
  {
    "z": 35,
    "a": 79,
    "symbol": "Br",
    "abundance": 50.65,
    "uncertainty": 0.09
  },
  {
    "z": 35,
    "a": 81,
    "symbol": "Br",
    "abundance": 49.35,
    "uncertainty": 0.09
  },
  {
    "z": 36,
    "a": 78,
    "symbol": "Kr",
    "abundance": 0.355,
    "uncertainty": 0.003
  },
  {
    "z": 36,
    "a": 80,
    "symbol": "Kr",
    "abundance": 2.286,
    "uncertainty": 0.01
  },
  {
    "z": 36,
    "a": 82,
    "symbol": "Kr",
    "abundance": 11.593,
    "uncertainty": 0.031
  },
  {
    "z": 36,
    "a": 83,
    "symbol": "Kr",
    "abundance": 11.5,
    "uncertainty": 0.019
  },
  {
    "z": 36,
    "a": 84,
    "symbol": "Kr",
    "abundance": 56.987,
    "uncertainty": 0.015
  },
  {
    "z": 36,
    "a": 86,
    "symbol": "Kr",
    "abundance": 17.279,
    "uncertainty": 0.041
  },
  {
    "z": 37,
    "a": 85,
    "symbol": "Rb",
    "abundance": 72.17,
    "uncertainty": 0.02
  },
  {
    "z": 37,
    "a": 87,
    "symbol": "Rb",
    "abundance": 27.83,
    "uncertainty": 0.02
  },
  {
    "z": 38,
    "a": 84,
    "symbol": "Sr",
    "abundance": 0.56,
    "uncertainty": 0.02
  },
  {
    "z": 38,
    "a": 86,
    "symbol": "Sr",
    "abundance": 9.86,
    "uncertainty": 0.2
  },
  {
    "z": 38,
    "a": 87,
    "symbol": "Sr",
    "abundance": 7,
    "uncertainty": 0.2
  },
  {
    "z": 38,
    "a": 88,
    "symbol": "Sr",
    "abundance": 82.58,
    "uncertainty": 0.35
  },
  {
    "z": 39,
    "a": 89,
    "symbol": "Y",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 40,
    "a": 90,
    "symbol": "Zr",
    "abundance": 51.45,
    "uncertainty": 0.04
  },
  {
    "z": 40,
    "a": 91,
    "symbol": "Zr",
    "abundance": 11.22,
    "uncertainty": 0.05
  },
  {
    "z": 40,
    "a": 92,
    "symbol": "Zr",
    "abundance": 17.15,
    "uncertainty": 0.03
  },
  {
    "z": 40,
    "a": 94,
    "symbol": "Zr",
    "abundance": 17.38,
    "uncertainty": 0.04
  },
  {
    "z": 40,
    "a": 96,
    "symbol": "Zr",
    "abundance": 2.8,
    "uncertainty": 0.02
  },
  {
    "z": 41,
    "a": 93,
    "symbol": "Nb",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 42,
    "a": 92,
    "symbol": "Mo",
    "abundance": 14.649,
    "uncertainty": 0.106
  },
  {
    "z": 42,
    "a": 94,
    "symbol": "Mo",
    "abundance": 9.187,
    "uncertainty": 0.033
  },
  {
    "z": 42,
    "a": 95,
    "symbol": "Mo",
    "abundance": 15.873,
    "uncertainty": 0.03
  },
  {
    "z": 42,
    "a": 96,
    "symbol": "Mo",
    "abundance": 16.673,
    "uncertainty": 0.008
  },
  {
    "z": 42,
    "a": 97,
    "symbol": "Mo",
    "abundance": 9.582,
    "uncertainty": 0.015
  },
  {
    "z": 42,
    "a": 98,
    "symbol": "Mo",
    "abundance": 24.292,
    "uncertainty": 0.08
  },
  {
    "z": 42,
    "a": 100,
    "symbol": "Mo",
    "abundance": 9.744,
    "uncertainty": 0.065
  },
  {
    "z": 44,
    "a": 96,
    "symbol": "Ru",
    "abundance": 5.54,
    "uncertainty": 0.14
  },
  {
    "z": 44,
    "a": 98,
    "symbol": "Ru",
    "abundance": 1.87,
    "uncertainty": 0.03
  },
  {
    "z": 44,
    "a": 99,
    "symbol": "Ru",
    "abundance": 12.76,
    "uncertainty": 0.14
  },
  {
    "z": 44,
    "a": 100,
    "symbol": "Ru",
    "abundance": 12.6,
    "uncertainty": 0.07
  },
  {
    "z": 44,
    "a": 101,
    "symbol": "Ru",
    "abundance": 17.06,
    "uncertainty": 0.02
  },
  {
    "z": 44,
    "a": 102,
    "symbol": "Ru",
    "abundance": 31.55,
    "uncertainty": 0.14
  },
  {
    "z": 44,
    "a": 104,
    "symbol": "Ru",
    "abundance": 18.62,
    "uncertainty": 0.27
  },
  {
    "z": 45,
    "a": 103,
    "symbol": "Rh",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 46,
    "a": 102,
    "symbol": "Pd",
    "abundance": 1.02,
    "uncertainty": 0.01
  },
  {
    "z": 46,
    "a": 104,
    "symbol": "Pd",
    "abundance": 11.14,
    "uncertainty": 0.08
  },
  {
    "z": 46,
    "a": 105,
    "symbol": "Pd",
    "abundance": 22.33,
    "uncertainty": 0.08
  },
  {
    "z": 46,
    "a": 106,
    "symbol": "Pd",
    "abundance": 27.33,
    "uncertainty": 0.03
  },
  {
    "z": 46,
    "a": 108,
    "symbol": "Pd",
    "abundance": 26.46,
    "uncertainty": 0.09
  },
  {
    "z": 46,
    "a": 110,
    "symbol": "Pd",
    "abundance": 11.72,
    "uncertainty": 0.09
  },
  {
    "z": 47,
    "a": 107,
    "symbol": "Ag",
    "abundance": 51.839,
    "uncertainty": 0.008
  },
  {
    "z": 47,
    "a": 109,
    "symbol": "Ag",
    "abundance": 48.161,
    "uncertainty": 0.008
  },
  {
    "z": 48,
    "a": 106,
    "symbol": "Cd",
    "abundance": 1.245,
    "uncertainty": 0.022
  },
  {
    "z": 48,
    "a": 108,
    "symbol": "Cd",
    "abundance": 0.888,
    "uncertainty": 0.011
  },
  {
    "z": 48,
    "a": 110,
    "symbol": "Cd",
    "abundance": 12.47,
    "uncertainty": 0.061
  },
  {
    "z": 48,
    "a": 111,
    "symbol": "Cd",
    "abundance": 12.795,
    "uncertainty": 0.012
  },
  {
    "z": 48,
    "a": 112,
    "symbol": "Cd",
    "abundance": 24.109,
    "uncertainty": 0.007
  },
  {
    "z": 48,
    "a": 113,
    "symbol": "Cd",
    "abundance": 12.227,
    "uncertainty": 0.007
  },
  {
    "z": 48,
    "a": 114,
    "symbol": "Cd",
    "abundance": 28.754,
    "uncertainty": 0.081
  },
  {
    "z": 48,
    "a": 116,
    "symbol": "Cd",
    "abundance": 7.512,
    "uncertainty": 0.054
  },
  {
    "z": 49,
    "a": 113,
    "symbol": "In",
    "abundance": 4.281,
    "uncertainty": 0.052
  },
  {
    "z": 49,
    "a": 115,
    "symbol": "In",
    "abundance": 95.719,
    "uncertainty": 0.052
  },
  {
    "z": 50,
    "a": 112,
    "symbol": "Sn",
    "abundance": 0.97,
    "uncertainty": 0.01
  },
  {
    "z": 50,
    "a": 114,
    "symbol": "Sn",
    "abundance": 0.66,
    "uncertainty": 0.01
  },
  {
    "z": 50,
    "a": 115,
    "symbol": "Sn",
    "abundance": 0.34,
    "uncertainty": 0.01
  },
  {
    "z": 50,
    "a": 116,
    "symbol": "Sn",
    "abundance": 14.54,
    "uncertainty": 0.09
  },
  {
    "z": 50,
    "a": 117,
    "symbol": "Sn",
    "abundance": 7.68,
    "uncertainty": 0.07
  },
  {
    "z": 50,
    "a": 118,
    "symbol": "Sn",
    "abundance": 24.22,
    "uncertainty": 0.09
  },
  {
    "z": 50,
    "a": 119,
    "symbol": "Sn",
    "abundance": 8.59,
    "uncertainty": 0.04
  },
  {
    "z": 50,
    "a": 120,
    "symbol": "Sn",
    "abundance": 32.58,
    "uncertainty": 0.09
  },
  {
    "z": 50,
    "a": 122,
    "symbol": "Sn",
    "abundance": 4.63,
    "uncertainty": 0.03
  },
  {
    "z": 50,
    "a": 124,
    "symbol": "Sn",
    "abundance": 5.79,
    "uncertainty": 0.05
  },
  {
    "z": 51,
    "a": 121,
    "symbol": "Sb",
    "abundance": 57.21,
    "uncertainty": 0.05
  },
  {
    "z": 51,
    "a": 123,
    "symbol": "Sb",
    "abundance": 42.79,
    "uncertainty": 0.05
  },
  {
    "z": 52,
    "a": 120,
    "symbol": "Te",
    "abundance": 0.09,
    "uncertainty": 0.01
  },
  {
    "z": 52,
    "a": 122,
    "symbol": "Te",
    "abundance": 2.55,
    "uncertainty": 0.12
  },
  {
    "z": 52,
    "a": 123,
    "symbol": "Te",
    "abundance": 0.89,
    "uncertainty": 0.03
  },
  {
    "z": 52,
    "a": 124,
    "symbol": "Te",
    "abundance": 4.74,
    "uncertainty": 0.14
  },
  {
    "z": 52,
    "a": 125,
    "symbol": "Te",
    "abundance": 7.07,
    "uncertainty": 0.15
  },
  {
    "z": 52,
    "a": 126,
    "symbol": "Te",
    "abundance": 18.84,
    "uncertainty": 0.25
  },
  {
    "z": 52,
    "a": 128,
    "symbol": "Te",
    "abundance": 31.74,
    "uncertainty": 0.08
  },
  {
    "z": 52,
    "a": 130,
    "symbol": "Te",
    "abundance": 34.08,
    "uncertainty": 0.62
  },
  {
    "z": 53,
    "a": 127,
    "symbol": "I",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 54,
    "a": 124,
    "symbol": "Xe",
    "abundance": 0.095,
    "uncertainty": 0.005
  },
  {
    "z": 54,
    "a": 126,
    "symbol": "Xe",
    "abundance": 0.089,
    "uncertainty": 0.003
  },
  {
    "z": 54,
    "a": 128,
    "symbol": "Xe",
    "abundance": 1.91,
    "uncertainty": 0.013
  },
  {
    "z": 54,
    "a": 129,
    "symbol": "Xe",
    "abundance": 26.401,
    "uncertainty": 0.138
  },
  {
    "z": 54,
    "a": 130,
    "symbol": "Xe",
    "abundance": 4.071,
    "uncertainty": 0.022
  },
  {
    "z": 54,
    "a": 131,
    "symbol": "Xe",
    "abundance": 21.232,
    "uncertainty": 0.051
  },
  {
    "z": 54,
    "a": 132,
    "symbol": "Xe",
    "abundance": 26.909,
    "uncertainty": 0.055
  },
  {
    "z": 54,
    "a": 134,
    "symbol": "Xe",
    "abundance": 10.436,
    "uncertainty": 0.035
  },
  {
    "z": 54,
    "a": 136,
    "symbol": "Xe",
    "abundance": 8.857,
    "uncertainty": 0.072
  },
  {
    "z": 55,
    "a": 133,
    "symbol": "Cs",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 56,
    "a": 130,
    "symbol": "Ba",
    "abundance": 0.11,
    "uncertainty": 0.01
  },
  {
    "z": 56,
    "a": 132,
    "symbol": "Ba",
    "abundance": 0.1,
    "uncertainty": 0.01
  },
  {
    "z": 56,
    "a": 134,
    "symbol": "Ba",
    "abundance": 2.42,
    "uncertainty": 0.15
  },
  {
    "z": 56,
    "a": 135,
    "symbol": "Ba",
    "abundance": 6.59,
    "uncertainty": 0.1
  },
  {
    "z": 56,
    "a": 136,
    "symbol": "Ba",
    "abundance": 7.85,
    "uncertainty": 0.24
  },
  {
    "z": 56,
    "a": 137,
    "symbol": "Ba",
    "abundance": 11.23,
    "uncertainty": 0.23
  },
  {
    "z": 56,
    "a": 138,
    "symbol": "Ba",
    "abundance": 71.7,
    "uncertainty": 0.29
  },
  {
    "z": 57,
    "a": 138,
    "symbol": "La",
    "abundance": 0.0888,
    "uncertainty": 0.0007
  },
  {
    "z": 57,
    "a": 139,
    "symbol": "La",
    "abundance": 99.9112,
    "uncertainty": 0.0007
  },
  {
    "z": 58,
    "a": 136,
    "symbol": "Ce",
    "abundance": 0.186,
    "uncertainty": 0.002
  },
  {
    "z": 58,
    "a": 138,
    "symbol": "Ce",
    "abundance": 0.251,
    "uncertainty": 0.002
  },
  {
    "z": 58,
    "a": 140,
    "symbol": "Ce",
    "abundance": 88.449,
    "uncertainty": 0.051
  },
  {
    "z": 58,
    "a": 142,
    "symbol": "Ce",
    "abundance": 11.114,
    "uncertainty": 0.051
  },
  {
    "z": 59,
    "a": 141,
    "symbol": "Pr",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 60,
    "a": 142,
    "symbol": "Nd",
    "abundance": 27.153,
    "uncertainty": 0.04
  },
  {
    "z": 60,
    "a": 143,
    "symbol": "Nd",
    "abundance": 12.173,
    "uncertainty": 0.026
  },
  {
    "z": 60,
    "a": 144,
    "symbol": "Nd",
    "abundance": 23.798,
    "uncertainty": 0.019
  },
  {
    "z": 60,
    "a": 145,
    "symbol": "Nd",
    "abundance": 8.293,
    "uncertainty": 0.012
  },
  {
    "z": 60,
    "a": 146,
    "symbol": "Nd",
    "abundance": 17.189,
    "uncertainty": 0.032
  },
  {
    "z": 60,
    "a": 148,
    "symbol": "Nd",
    "abundance": 5.756,
    "uncertainty": 0.021
  },
  {
    "z": 60,
    "a": 150,
    "symbol": "Nd",
    "abundance": 5.638,
    "uncertainty": 0.028
  },
  {
    "z": 62,
    "a": 144,
    "symbol": "Sm",
    "abundance": 3.08,
    "uncertainty": 0.04
  },
  {
    "z": 62,
    "a": 147,
    "symbol": "Sm",
    "abundance": 15,
    "uncertainty": 0.14
  },
  {
    "z": 62,
    "a": 148,
    "symbol": "Sm",
    "abundance": 11.25,
    "uncertainty": 0.09
  },
  {
    "z": 62,
    "a": 149,
    "symbol": "Sm",
    "abundance": 13.82,
    "uncertainty": 0.1
  },
  {
    "z": 62,
    "a": 150,
    "symbol": "Sm",
    "abundance": 7.37,
    "uncertainty": 0.09
  },
  {
    "z": 62,
    "a": 152,
    "symbol": "Sm",
    "abundance": 26.74,
    "uncertainty": 0.09
  },
  {
    "z": 62,
    "a": 154,
    "symbol": "Sm",
    "abundance": 22.74,
    "uncertainty": 0.14
  },
  {
    "z": 63,
    "a": 151,
    "symbol": "Eu",
    "abundance": 47.81,
    "uncertainty": 0.06
  },
  {
    "z": 63,
    "a": 153,
    "symbol": "Eu",
    "abundance": 52.19,
    "uncertainty": 0.06
  },
  {
    "z": 64,
    "a": 152,
    "symbol": "Gd",
    "abundance": 0.2,
    "uncertainty": 0.03
  },
  {
    "z": 64,
    "a": 154,
    "symbol": "Gd",
    "abundance": 2.18,
    "uncertainty": 0.02
  },
  {
    "z": 64,
    "a": 155,
    "symbol": "Gd",
    "abundance": 14.8,
    "uncertainty": 0.09
  },
  {
    "z": 64,
    "a": 156,
    "symbol": "Gd",
    "abundance": 20.47,
    "uncertainty": 0.03
  },
  {
    "z": 64,
    "a": 157,
    "symbol": "Gd",
    "abundance": 15.65,
    "uncertainty": 0.04
  },
  {
    "z": 64,
    "a": 158,
    "symbol": "Gd",
    "abundance": 24.84,
    "uncertainty": 0.08
  },
  {
    "z": 64,
    "a": 160,
    "symbol": "Gd",
    "abundance": 21.86,
    "uncertainty": 0.03
  },
  {
    "z": 65,
    "a": 159,
    "symbol": "Tb",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 66,
    "a": 156,
    "symbol": "Dy",
    "abundance": 0.056,
    "uncertainty": 0.003
  },
  {
    "z": 66,
    "a": 158,
    "symbol": "Dy",
    "abundance": 0.095,
    "uncertainty": 0.003
  },
  {
    "z": 66,
    "a": 160,
    "symbol": "Dy",
    "abundance": 2.329,
    "uncertainty": 0.018
  },
  {
    "z": 66,
    "a": 161,
    "symbol": "Dy",
    "abundance": 18.889,
    "uncertainty": 0.042
  },
  {
    "z": 66,
    "a": 162,
    "symbol": "Dy",
    "abundance": 25.475,
    "uncertainty": 0.036
  },
  {
    "z": 66,
    "a": 163,
    "symbol": "Dy",
    "abundance": 24.896,
    "uncertainty": 0.042
  },
  {
    "z": 66,
    "a": 164,
    "symbol": "Dy",
    "abundance": 28.26,
    "uncertainty": 0.054
  },
  {
    "z": 67,
    "a": 165,
    "symbol": "Ho",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 68,
    "a": 162,
    "symbol": "Er",
    "abundance": 0.139,
    "uncertainty": 0.005
  },
  {
    "z": 68,
    "a": 164,
    "symbol": "Er",
    "abundance": 1.601,
    "uncertainty": 0.003
  },
  {
    "z": 68,
    "a": 166,
    "symbol": "Er",
    "abundance": 33.503,
    "uncertainty": 0.036
  },
  {
    "z": 68,
    "a": 167,
    "symbol": "Er",
    "abundance": 22.869,
    "uncertainty": 0.009
  },
  {
    "z": 68,
    "a": 168,
    "symbol": "Er",
    "abundance": 26.978,
    "uncertainty": 0.018
  },
  {
    "z": 68,
    "a": 170,
    "symbol": "Er",
    "abundance": 14.91,
    "uncertainty": 0.036
  },
  {
    "z": 69,
    "a": 169,
    "symbol": "Tm",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 70,
    "a": 168,
    "symbol": "Yb",
    "abundance": 0.123,
    "uncertainty": 0.003
  },
  {
    "z": 70,
    "a": 170,
    "symbol": "Yb",
    "abundance": 2.982,
    "uncertainty": 0.039
  },
  {
    "z": 70,
    "a": 171,
    "symbol": "Yb",
    "abundance": 14.086,
    "uncertainty": 0.14
  },
  {
    "z": 70,
    "a": 172,
    "symbol": "Yb",
    "abundance": 21.686,
    "uncertainty": 0.13
  },
  {
    "z": 70,
    "a": 173,
    "symbol": "Yb",
    "abundance": 16.103,
    "uncertainty": 0.063
  },
  {
    "z": 70,
    "a": 174,
    "symbol": "Yb",
    "abundance": 32.025,
    "uncertainty": 0.08
  },
  {
    "z": 70,
    "a": 176,
    "symbol": "Yb",
    "abundance": 12.995,
    "uncertainty": 0.083
  },
  {
    "z": 71,
    "a": 175,
    "symbol": "Lu",
    "abundance": 97.401,
    "uncertainty": 0.013
  },
  {
    "z": 71,
    "a": 176,
    "symbol": "Lu",
    "abundance": 2.599,
    "uncertainty": 0.013
  },
  {
    "z": 72,
    "a": 174,
    "symbol": "Hf",
    "abundance": 0.16,
    "uncertainty": 0.12
  },
  {
    "z": 72,
    "a": 176,
    "symbol": "Hf",
    "abundance": 5.26,
    "uncertainty": 0.7
  },
  {
    "z": 72,
    "a": 177,
    "symbol": "Hf",
    "abundance": 18.6,
    "uncertainty": 0.16
  },
  {
    "z": 72,
    "a": 178,
    "symbol": "Hf",
    "abundance": 27.28,
    "uncertainty": 0.28
  },
  {
    "z": 72,
    "a": 179,
    "symbol": "Hf",
    "abundance": 13.62,
    "uncertainty": 0.11
  },
  {
    "z": 72,
    "a": 180,
    "symbol": "Hf",
    "abundance": 35.08,
    "uncertainty": 0.33
  },
  {
    "z": 73,
    "a": 181,
    "symbol": "Ta",
    "abundance": 99.988,
    "uncertainty": 0.0003
  },
  {
    "z": 74,
    "a": 180,
    "symbol": "W",
    "abundance": 0.12,
    "uncertainty": 0.01
  },
  {
    "z": 74,
    "a": 182,
    "symbol": "W",
    "abundance": 26.5,
    "uncertainty": 0.16
  },
  {
    "z": 74,
    "a": 183,
    "symbol": "W",
    "abundance": 14.31,
    "uncertainty": 0.04
  },
  {
    "z": 74,
    "a": 184,
    "symbol": "W",
    "abundance": 30.64,
    "uncertainty": 0.02
  },
  {
    "z": 74,
    "a": 186,
    "symbol": "W",
    "abundance": 28.43,
    "uncertainty": 0.19
  },
  {
    "z": 75,
    "a": 185,
    "symbol": "Re",
    "abundance": 37.4,
    "uncertainty": 0.05
  },
  {
    "z": 75,
    "a": 187,
    "symbol": "Re",
    "abundance": 62.6,
    "uncertainty": 0.05
  },
  {
    "z": 76,
    "a": 184,
    "symbol": "Os",
    "abundance": 0.02,
    "uncertainty": 0.02
  },
  {
    "z": 76,
    "a": 186,
    "symbol": "Os",
    "abundance": 1.59,
    "uncertainty": 0.64
  },
  {
    "z": 76,
    "a": 187,
    "symbol": "Os",
    "abundance": 1.96,
    "uncertainty": 0.17
  },
  {
    "z": 76,
    "a": 188,
    "symbol": "Os",
    "abundance": 13.24,
    "uncertainty": 0.27
  },
  {
    "z": 76,
    "a": 189,
    "symbol": "Os",
    "abundance": 16.15,
    "uncertainty": 0.23
  },
  {
    "z": 76,
    "a": 190,
    "symbol": "Os",
    "abundance": 26.26,
    "uncertainty": 0.2
  },
  {
    "z": 76,
    "a": 192,
    "symbol": "Os",
    "abundance": 40.78,
    "uncertainty": 0.32
  },
  {
    "z": 77,
    "a": 191,
    "symbol": "Ir",
    "abundance": 37.3,
    "uncertainty": 0.2
  },
  {
    "z": 77,
    "a": 193,
    "symbol": "Ir",
    "abundance": 62.7,
    "uncertainty": 0.2
  },
  {
    "z": 78,
    "a": 190,
    "symbol": "Pt",
    "abundance": 0.012,
    "uncertainty": 0.002
  },
  {
    "z": 78,
    "a": 192,
    "symbol": "Pt",
    "abundance": 0.782,
    "uncertainty": 0.024
  },
  {
    "z": 78,
    "a": 194,
    "symbol": "Pt",
    "abundance": 32.864,
    "uncertainty": 0.41
  },
  {
    "z": 78,
    "a": 195,
    "symbol": "Pt",
    "abundance": 33.775,
    "uncertainty": 0.24
  },
  {
    "z": 78,
    "a": 196,
    "symbol": "Pt",
    "abundance": 25.211,
    "uncertainty": 0.34
  },
  {
    "z": 78,
    "a": 198,
    "symbol": "Pt",
    "abundance": 7.356,
    "uncertainty": 0.13
  },
  {
    "z": 79,
    "a": 197,
    "symbol": "Au",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 80,
    "a": 196,
    "symbol": "Hg",
    "abundance": 0.15,
    "uncertainty": 0.01
  },
  {
    "z": 80,
    "a": 198,
    "symbol": "Hg",
    "abundance": 10.04,
    "uncertainty": 0.03
  },
  {
    "z": 80,
    "a": 199,
    "symbol": "Hg",
    "abundance": 16.94,
    "uncertainty": 0.12
  },
  {
    "z": 80,
    "a": 200,
    "symbol": "Hg",
    "abundance": 23.14,
    "uncertainty": 0.09
  },
  {
    "z": 80,
    "a": 201,
    "symbol": "Hg",
    "abundance": 13.17,
    "uncertainty": 0.09
  },
  {
    "z": 80,
    "a": 202,
    "symbol": "Hg",
    "abundance": 29.74,
    "uncertainty": 0.13
  },
  {
    "z": 80,
    "a": 204,
    "symbol": "Hg",
    "abundance": 6.82,
    "uncertainty": 0.04
  },
  {
    "z": 81,
    "a": 203,
    "symbol": "Tl",
    "abundance": 29.515,
    "uncertainty": 0.044
  },
  {
    "z": 81,
    "a": 205,
    "symbol": "Tl",
    "abundance": 70.485,
    "uncertainty": 0.044
  },
  {
    "z": 82,
    "a": 204,
    "symbol": "Pb",
    "abundance": 1.4,
    "uncertainty": 0.6
  },
  {
    "z": 82,
    "a": 206,
    "symbol": "Pb",
    "abundance": 24.1,
    "uncertainty": 3
  },
  {
    "z": 82,
    "a": 207,
    "symbol": "Pb",
    "abundance": 22.1,
    "uncertainty": 5
  },
  {
    "z": 82,
    "a": 208,
    "symbol": "Pb",
    "abundance": 52.4,
    "uncertainty": 7
  },
  {
    "z": 83,
    "a": 209,
    "symbol": "Bi",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 90,
    "a": 230,
    "symbol": "Th",
    "abundance": 0.02,
    "uncertainty": 0.02
  },
  {
    "z": 90,
    "a": 232,
    "symbol": "Th",
    "abundance": 99.98,
    "uncertainty": 0.02
  },
  {
    "z": 91,
    "a": 231,
    "symbol": "Pa",
    "abundance": 100,
    "uncertainty": null
  },
  {
    "z": 92,
    "a": 234,
    "symbol": "U",
    "abundance": 0.0054,
    "uncertainty": 0.0005
  },
  {
    "z": 92,
    "a": 235,
    "symbol": "U",
    "abundance": 0.7204,
    "uncertainty": 0.0006
  },
  {
    "z": 92,
    "a": 238,
    "symbol": "U",
    "abundance": 99.2742,
    "uncertainty": 0.001
  }
] as const

/**
 * Get IAEA abundance data for a specific element
 * @param elementSymbol - Element symbol (e.g., 'H', 'Li', 'Ni')
 * @returns Array of IAEAAbundance entries for that element
 */
export function getIAEAAbundancesForElement(elementSymbol: string): IAEAAbundance[] {
  // Handle hydrogen isotopes: D and T map back to H for lookup
  const lookupSymbol = (elementSymbol === 'D' || elementSymbol === 'T') ? 'H' : elementSymbol

  return IAEA_ABUNDANCES.filter((a) => {
    // For hydrogen, match by symbol since we store D/T separately
    if (lookupSymbol === 'H') {
      return a.symbol === elementSymbol
    }
    return a.symbol === lookupSymbol
  })
}

/**
 * Get IAEA abundance for a specific nuclide
 * @param symbol - Element symbol (e.g., 'Li', 'D')
 * @param massNumber - Mass number A
 * @returns Abundance percentage or null if not found
 */
export function getIAEAAbundance(symbol: string, massNumber: number): number | null {
  const entry = IAEA_ABUNDANCES.find((a) => a.symbol === symbol && a.a === massNumber)
  return entry ? entry.abundance : null
}

/** Metadata about this IAEA data extraction */
export const IAEA_METADATA = {
  source: 'IAEA Nuclear Data Services - LiveChart API',
  url: 'https://nds.iaea.org/relnsd/v1/data',
  dataVintage: 'NuBase 2020',
  extractionDate: '2026-03-02',
  nuclideCount: 288,
  elementCount: 84,
} as const
